# service-discovery/Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN pip install flask

EXPOSE 8500

CMD ["python", "service-discovery.py"]
